### user 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
    client.global.set("refresh_token", response.body.data.refreshToken);
%}

### user2 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "password"
}

> {% client.global.set("access_token2", response.body.data.accessToken) %}

### email 계정으로 게시글 생성 (draft)
POST localhost:8080/api/posts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "description": "description"
}

> {% client.global.set("post_id", response.body.data.id) %}


### email 계정으로 좋아요 -> 실패해야함. 예외문구: 존재하지 않는 게시글 (상태가 이상하다.. 보다는 존재하지 않는다는게 맞을듯)
POST localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token}}

### email 계정으로 이전 게시글 상태 published
PATCH localhost:8080/api/posts/{{post_id}}/status
AUthorization: Bearer {{access_token}}
Content-Type: application/json

{
  "status": "PUBLISHED"
}

### user2 계정으로 좋아요 -> 성공해야함.
POST localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token2}}

### user2 계정으로 좋아요 -> 성공해야함.
GET localhost:8080/api/posts/{{post_id}}
Authorization: Bearer {{access_token2}}


### user2 계정으로 다시 좋아요 -> 400 예외. 이미 좋아요 함
POST localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token2}}

### user2 계정으로 좋아요 취소 -> 성공
DELETE localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token2}}

### user2 계정으로 다시 좋아요 취소 -> 실패. 400 또는 404 예외 발생해야함
DELETE localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token2}}

### user 계정으로 게시글 삭제
DELETE localhost:8080/api/posts/{{post_id}}
Authorization: Bearer {{access_token}}

### user2 계정으로 삭제 된 게시글 좋아요 -> 실패 400 예외 발생해야함
POST localhost:8080/api/posts/{{post_id}}/like
Authorization: Bearer {{access_token2}}

### 조회
GET localhost:8080/api/posts/{{post_id}}
