version: '3.8'

services:
  test-db:
    container_name: "bespoke-test"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bespoke
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "23306:3306"
  test-redis:
    image: "redis:latest"
    container_name: "redis-server"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:6379"
  test-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "25672:5672"
      - "35672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

