version: '3.8'

services:
  db:
    container_name: "bespoke"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bespoke
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
  test-db:
    container_name: "bespoke-test"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bespoke
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "23306:3306"
