jwt:
  secret-key: ${JWT_SECRET_KEY}
spring:
  application:
    name: bespoke
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/bespoke
    username: root
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    locations: classpath:db/migration,classpath:db/seed
    user: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
