jwt:
  secret-key: ${JWT_SECRET_KEY}
host:
  url: ${HOST_URL}
rabbitmq.routing-key.mail: mail
rabbitmq.routing-key.common: common
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,
    brotli: true
aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET}
    bucket-url: ${AWS_S3_BUCKET_URL}
spring:
  application:
    name: bespoke
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/bespoke
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    locations: classpath:db/migration,classpath:db/seed
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
  rabbitmq:
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
